jobs:
  build-upload:
    docker:
      - image: docker:19.03.8
    environment:
      IMAGE_NAME: bayu3490/vokasi_binadesa2020-backend
    working_directory: /app
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Give version tag to Docker Image
          command: IMAGE_NAME=${IMAGE_NAME}:`cat VERSION`

      - run:
          name: Build Docker Image
          command: docker build -t $IMAGE_NAME .

      - run:
          name: Authentication to Container Registry
          command: echo $access_token | docker login --username bayu3490 --password-stdin

      - run:
          name: Pushing Docker Image to Container Registry
          command: docker push $IMAGE_NAME

workflows:
  version: 2
  build-and-upload:
    jobs:
      - build-upload:
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/